title: "Plebware Control Centre"
author: "Otto Brinkmeier"
description: "Plebware: accessible, repairable, understandable technology"
baseurl: ""
url: "https://Plebware.github.io"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: Plebware/pleb-theme

collections:
  fiction:
    output: true
    permalink: /fiction/:path/
  devotions:
    output: true
    permalink: /devotions/:path/
  journals:
    output: true
    permalink: /journals/:path/
  creative:
    output: true
    permalink: /creative/:path/

defaults:
  - scope:
      path: ""
      type: fiction
    values:
      layout: post
  - scope:
      path: ""
      type: devotions
    values:
      layout: post
  - scope:
      path: ""
      type: journals
    values:
      layout: post
  - scope:
      path: ""
      type: creative
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
